# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUl3lpxc3VfglXZBPngmDL9mTT5ygOsd
"""

import os
import shutil
from google.colab import drive

# --- 1. Mount Your Drive ---
drive.mount('/content/drive')

# --- 2. Run the REAL Copy Command ---
# This is the 15-20 minute copy.
print("Starting the REAL copy of all .npy files from Drive to local disk...")
!cp -r "/content/drive/MyDrive/UCF101_Sports_NPY_Full"/. /content/UCF101_Sports_NPY_Full
print("Data is now TRULY local! Ready for fast training.")

# Verify the files are here:
!ls /content/UCF101_Sports_NPY_Full